[workspace]
resolver = "2"

members = [
    "bin/node",
    "bin/node-dev",

    "core-primitives",

    "pallets/contracts",

    "runtime/common",
    "runtime/dev",
    "runtime/patracts",
]

[profile.release]
panic = "unwind"

